/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface SignatureCheckResult {
  valid: boolean
  detectedType?: string
  detectedMime?: string
  error?: string
}
export declare function validateFileSignature(filepath: string): SignatureCheckResult
export interface ProcessMediaResult {
  success: boolean
  outputPath?: string
  error?: string
}
/** Uses standard ffmpeg subprocess wrapped safely in Rust to avoid Node.js memory overhead */
export declare function extractAndCompressAudio(inputPath: string, outputPath: string): Promise<ProcessMediaResult>
